# Generated by Django 4.0.1 on 2022-09-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0002_alter_reg_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='log_user',
            fields=[
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
