# Generated by Django 4.0.1 on 2022-09-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0003_log_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
