# Generated by Django 4.0.1 on 2022-09-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0004_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='log',
        ),
    ]
